### ISSUE TITLE
"自动下载v2ray"无响应

### ISSUE THREAD

**Issue by WenSong-L** [josephpei/uv2ray#2]
网太差拉不下来？
在 "选择v2ray目录" 填了pacman安装的v2ray，这样ok吗大佬

**Comment by josephpei** [comment]
自动下载v2ray功能尚未实现，选择v2ray目录里要有名为 v2ray 可执行文件，且目录要有写权限

目前建议自己建个目录，下载并重命名 v2ray

**Comment by josephpei** [comment]
现在去掉了自动下载 v2ray 功能，添加使用系统v2ray选项，如果使用系统v2ray，生成的配置文件路径为 $HOME/.config/uv2ray/config.json，执行命令为 v2ray -config=$HOME/.config/uv2ray/config.json

**Comment by WenSong-L** [comment]
> 现在去掉了自动下载 v2ray 功能，添加使用系统v2ray选项，如果使用系统v2ray，生成的配置文件路径为 $HOME/.config/uv2ray/config.json，执行命令为 v2ray -config=$HOME/.config/uv2ray/config.json

好的，感谢大佬
